/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import com.mycompany.cuestionario.Cuestionario;
import java.util.Random;

/**
 *
 * @author th3tici
 */
public class Preguntas extends javax.swing.JFrame {
    Random numeroAleatorio;
    int preguntaActual;
    Cuestionario preguntas [];
    int cantPreguntas; 
    int respuestasCorrectas; 
    /**
     * Creates new form Preguntas
     */
    public Preguntas() {
        initComponents();
        preguntas = new Cuestionario [10];
        preguntas[0] = new Cuestionario("Programming language is the communication tool between User-Computer", "True");
        preguntas[1] = new Cuestionario("Java is an object oriented language", "True");
        preguntas[2] = new Cuestionario("In python <<Printf>> is used", "False");
        preguntas[3] = new Cuestionario("If we need the user to enter an integer we use <<float>>", "False");
        preguntas[4] = new Cuestionario("C++ was designed in 1979", "True");
        preguntas[5] = new Cuestionario("The hardware is the logical part of the computer", "False");
        preguntas[6] = new Cuestionario("Python is low level lenguage used to develop apps", "False");
        preguntas[7] = new Cuestionario("Attributes are pieces of information that an objects knows about itself", "True");
        preguntas[8] = new Cuestionario("With C++ we can develop a game like minecraft Windows 10", "True");
        preguntas[9] = new Cuestionario("<<toString>> is used to store information and not show it to the user", "False");
        numeroAleatorio = new Random();
        
        cantPreguntas = 0; 
        respuestasCorrectas = 0; 
        
        preguntaActual = numeroAleatorio.nextInt(10);
        lblPreguntas.setText(preguntas[preguntaActual].getPregunta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRTrue = new javax.swing.JRadioButton();
        jRFalse = new javax.swing.JRadioButton();
        lblPreguntas = new javax.swing.JLabel();
        btnverificar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRTrue);
        jRTrue.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        jRTrue.setText("True");

        buttonGroup1.add(jRFalse);
        jRFalse.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        jRFalse.setText("False");

        lblPreguntas.setText("jLabel2");

        btnverificar.setText("check");
        btnverificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnverificar)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRTrue)
                    .addComponent(jRFalse)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(jRTrue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRFalse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnverificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnverificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverificarActionPerformed
        // TODO add your handling code here:
        cantPreguntas ++;
      
        if (preguntas[preguntaActual].getRespuestaCorrecta() == "True" && this.jRTrue.isSelected()) {
            respuestasCorrectas ++;
            lblResultado.setText("The previous answer is Correct");
        }else{
          
         if (preguntas[preguntaActual].getRespuestaCorrecta() == "False" && this.jRFalse.isSelected()) {
             respuestasCorrectas ++; 
        }else{
             lblResultado.setText("The previous answer is Incorrect");
        }
        }
        if (cantPreguntas < 20){
        preguntaActual = numeroAleatorio.nextInt(10);
        lblPreguntas.setText(preguntas[preguntaActual].getPregunta());
        }else{
            new Resultado(respuestasCorrectas).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnverificarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnverificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRFalse;
    private javax.swing.JRadioButton jRTrue;
    private javax.swing.JLabel lblPreguntas;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
